### ISSUE TITLE
Generated deployment folder how to DocumentRoot

### ISSUE THREAD

**Issue by apapazisis** [papertank/envoy-deploy#12]
The generated deployed folder can be

`20150317110501/`
`20150317114500/`
`current -> ./20150317114500`
`storage/`
`.env`

and you set as root folder `root /home/forge/example.com/current/public;`

Should not be the root path `root /home/forge/example.com/current/20150317114500/public;`??

I am using apache and facing this issue because for each deploymend the folder name is changed and root must be changed. 

I guess the symbolic link should be created with the command
`ln -nfs {{ $release_dir }}/* {{ $app_path }}/current`

**Comment by davidrushton** [comment]
Hi @apapazisis 

No, your apache / nginx root should be set to just `current/public`. This is because the `current` directory should be symlinked to the latest release - in the example above `current/public` is the same as `20150317114500/public`, but your host config points to current so that you don't have to always change that.

If you're not seeing the latest deployment when you hit your site, you might need to restart php-fpm in your `deployment_finish` task. This might be `sudo service php-fpm reload` or `sudo service php7.2-fpm reload`, depending on your setup.

Hope that helps!
